apiVersion: v1
kind: Secret
metadata:
  name: cluster1-s3-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVNWUlFCNkZGWlJaQUFYTkc=
  AWS_SECRET_ACCESS_KEY: M1ZGNmJPL1RVMzI2YnhRanlsRlhnN2FSZytWVnp1Vi9EZWt5SmFXbA==
