apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
type: Opaque
stringData:
  root: root_password
  xtrabackup: backup_password
  monitor: monitor_password
  pmmserverkey: ZXlKcklqb2lielpDYnpKbWNIaDZlalF4T1dWNk5rNVJjbEZIWTJKYWVIZFlNbE5qVm5VaUxDSnVJam9pY0cxdElpd2lhV1FpT2pGOQ==
  operator: operator_password
  replication: replication_password
  orchestrator: orchestrator_password
  heartbeat: heartbeat_password
