apiVersion: v1
kind: Secret
metadata:
  name: cluster1-secrets
type: Opaque
stringData:
  # pmmserverkey: ZXlKcklqb2lRMHBCV1RGRVpIVnVla3hXV0VoWE1sbEpkV2hoYzBVek5FTkdiVkExY2xvaUxDSnVJam9pY0cxdElpd2lhV1FpT2pGOQ==
  root: root_password
  xtrabackup: backup_password
  monitor: monitory
  clustercheck: clustercheckpassword
  proxyadmin: admin_password
  pmmserverkey: YWRtaW4=
  operator: operatoradmin
  replication: repl_password
